name: Auto Commit Github
on:
  push:
    branches:
      - main
  schedule:
    - cron: "* */6 * * *"
jobs:
   acg:
    name: Auto Green
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
          python-version: '3.10'
    - name: Setup Git Config
      run: git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com" && git config --local user.name "${GITHUB_ACTOR}"
    - name: Run Python Code
      run: python main.py
